---
swagger: "2.0"
info:
  description: The product of a tutorial on goswagger.io
  title: A To Do list application
  version: 1.0.0
schemes:
- http
- https
paths:
  /profile:
    get:
      tags:
        - todos
      parameters:
        - name: name
          in: query
          type: string
          format: string
        - name: gender
          in: query
          type: string
          format: string
          default: "queer"
      responses:
        200:
          description: List the users of Peakly
          schema:
            type: array
            items:
              $ref: "#/definitions/profile"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
definitions:
  profile:
    type: object
    required:
      - description
    properties:
      id:
        type: string
        format: string
        readOnly: true
      description:
        type: string
        minLength: 1
      completed:
        type: boolean
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string